stages:
  - deploy

deploy_gcp:
  stage: deploy
  environment: gcp
  before_script:
    - gcloud auth activate-service-account --key-file=$GCP_AUTH_USER
  script:
    - gcloud config set project $PROJECT_ID --quiet
    - bash $1 $2 $3 $4 $5 $6
  when: manual
  only:
    - main